Repository reposaur/reposaur, pull requests merged in 2022-04, with the labels that each got.

#4 feat: throttle requests to gh on secondary rate limits
  pkg/sdk/sdk.go
  pkg/util/http.go
Labels: enhancement

#7 docs: fix all organization repositories example
  README.md
Labels: documentation

#11 fix(errors): error abstractions refactoring
  internal/policy/engine.go
  internal/policy/errors.go
Labels: enhancement, good first issue

#9 feat: improved logging
  cmd/reposaur/reposaur.go
  pkg/sdk/sdk.go
  pkg/util/http.go
Labels: enhancement

#13 feat: restructure cli
  .goreleaser.yml
  README.md
  cmd/rsr/rsr.go
  install.sh
  main.go
  pkg/cmd/exec/exec.go
  pkg/cmd/root/root.go
  pkg/cmdutil/factory.go
  pkg/sdk/sdk.go
  pkg/util/http.go
Labels: enhancement

#17 build: temp fix before release
  install.sh
Labels: bug
